export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  NOTICES: '/notices',
  NOTICE_DETAIL: '/notices/:id',
  EVENTS: '/events',
  EVENT_DETAIL: '/events/:id',
  ACHIEVEMENTS: '/achievements',
  FACULTY: '/faculty',
  ALUMNI: '/alumni',
  SOCIETY: '/society',
  STUDENTS: '/students',
  STUDENT_PROFILE: '/students/:id',
  PROFILE: '/profile',
  FINANCE: '/finance',
  IMPORTANT_DATA: '/important-data',
  WORK_ASSIGNMENTS: '/work-assignments',
  ADMIN: '/admin',
} as const;
