CREATE TABLE student_profiles (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
    headline          VARCHAR(300),
    about             TEXT,
    cgpa              DECIMAL(3,2),
    github_url        VARCHAR(500),
    linkedin_url      VARCHAR(500),
    portfolio_url     VARCHAR(500),
    resume_url        TEXT,
    skills            JSONB DEFAULT '[]',
    experience        JSONB DEFAULT '[]',
    projects          JSONB DEFAULT '[]',
    education         JSONB DEFAULT '[]',
    certifications    JSONB DEFAULT '[]',
    languages         JSONB DEFAULT '[]',
    is_looking_for_job BOOLEAN DEFAULT FALSE,
    job_preferences   JSONB DEFAULT '{}',
    visibility        VARCHAR(20) DEFAULT 'public',
    updated_at        TIMESTAMPTZ DEFAULT NOW()
);
